### ISSUE TITLE
tokenlist is being fetched  too often

### ISSUE THREAD

**Issue by schmanu** [bh2smith/safe-airdrop#104]
Currently the tokenList is being fetched on every(?) render which is definitely not what we want.

I would want to refactor the whole tokenList structure a bit so that everything is memoized / cached correctly.

**Comment by bh2smith** [comment]
Amazing idea. Great catch.

**Comment by bh2smith** [comment]
Hey @schmanu - is this something we have already taken care of with caching? I can't recall if its been done already or not.

**Comment by schmanu** [comment]
I think this should not be an issue anymore.
I'll close the issue.
