### ISSUE TITLE
How many airdrops per transaction can I do?

### ISSUE THREAD

**Issue by canercak** [bh2smith/safe-airdrop#14]
Hi,
Thanks for the app. I'm trying to find out how many airdrops per transaction can I send?. I have to do batch airdrops like thousands of them and you know the gas fees are high these days. Other solutions normally can do up to 150 airdrops per transaction, how much is this going to do? After I create a safe, can I batch transfer 1000s of airdrops in a single safe transaction?

**Comment by bh2smith** [comment]
You should be able to do about 200 maybe 220 before you reach about 60% of the block gas limit. I made a benchmark for this in another repo. I will dig this up for you. Thanks for the great question!


Of course you can always try to go for higher block limits, but it is unlikely that your block will be mined without a very high gas price.

**Comment by bh2smith** [comment]
Here is the test for an equivalent transaction that pushes the number of transactions to 50% of the block gas limit:

https://github.com/gnosis/dex-liquidity-provision/blob/67a887952631da11e0b5f40dc551d121a04b8be4/test/scripts/test_airdrop.js#L128-L169

**Comment by bh2smith** [comment]
Actually this test used a gas cap of 4M and managed to squeeze in 213 transfers. Of course the gas consumed for a transfer also depends on the token you are sending as they may implement the transfer function differently than others.

**Comment by canercak** [comment]
understood..thank you for the detailed explanation
