### ISSUE TITLE
xdai: network does not support ENS

### ISSUE THREAD

**Issue by PeterTheOne** [bh2smith/safe-airdrop#152]
Gnosis Safe CSV Airdrop app doesn't work on xdai :cry:

`network does not support ENS (operation="ENS", network="xdai", code=UNSUPPORTED_OPERATION, version=providers/5.4.0)`

Even without ENS I would expect that I can send to addresses without ENS.

**Comment by schmanu** [comment]
Thanks for reporting this issue. 

I won't be able to work on it this week, but will fix this bug the week after and publish a new version.

**Comment by bh2smith** [comment]
> I won't be able to work on it this week, but will fix this bug the week after and publish a new version. 

We should probably also double check that it's still works with rinkeby at the same time as I suspect this is probably a current issue there as well.

**Comment by schmanu** [comment]
> We should probably also double check that it's still works with rinkeby at the same time as I suspect this is probably a current issue there as well.

On Rinkeby everything works fine for me.
But fixing this on xdai will also fix it on any other network where ens is not supported.

**Comment by schmanu** [comment]
The issue is fixed in the next release. I'll ping here when the next version is published and available in the gnosis safe apps.

**Comment by schmanu** [comment]
@PeterTheOne 
The app has been updated in the gnosis safe apps.
You should be able to use it now on xDai network.

Thanks for submitting this bug report!
