### ISSUE TITLE
Support for NFT transfers

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/safe-airdrop#16]
Given that NFTs have now hit the scene, it shouldn't be too difficult to support NFT airdrops.

**Comment by bh2smith** [comment]
We should probably follow the ERC721 token standard if we want to support this:

https://ethereum.org/en/developers/docs/standards/tokens/erc-721/

**Comment by arberx** [comment]
This would be awesome. Currently looking for a solution to send multiple NFTs to multiple addresses using a gnosis safe.

**Comment by bh2smith** [comment]
- Great to hear your enthusiasm @arberx, this will likely be a quite involved task UI-wise but is actually quite simple from a backend standpoint. I will gather a few points in the code, where we batch together the erc20 transfers for guidance, but essentially we parse the CSV with rows containing (NFT address, recipient) columns and encode each row as an NFT transfer, then throw it all into a gnosis safe "multi send" transaction and voila. We would also have to import or hard code the ERC721 contract artifacts to be able to encode the transfer method, but probably only the interface contract is needed. 

Of course we should implement validations that the safe itself actually owns the tokens it seeks to transfer and give a fair warning beforehand. 

From the UI side, we were thinking that NFT transfers should actually be a separate tab so to distinguish between the different CSV types, but now that I think of it, since we assume ETH transfer when the token address field is null, we could also assume NFT transfer whenever the amount field is null. This way we could actually batch together all three types of airdrops (erc20, native token and NFT)into a single transfer!

**Comment by bh2smith** [comment]
This is the code block which builds transfers from a list of `Payment`

https://github.com/bh2smith/safe-airdrop/blob/084abdc60f559424c16cd4676b35a1b93300a383/src/transfers.ts#L7-L28

Note that once the CSV is uploaded, during parsing, we convert each row into a "Payment" object.

**Comment by arberx** [comment]
Thanks for the quick response and detailed explanation!

The contract work seems straightforward, but don't think I can commit to the front-end at the moment. Also, it seems the [transaction builder](https://help.gnosis-safe.io/en/articles/4680071-transaction-builder) app supports erc721's although there isn't a good example...

**Comment by bh2smith** [comment]
> The contract work seems straightforward, but don't think I can commit to the front-end at the moment.
This is something that @schmanu might be interested in helping out with. Feel free to implement the backend anyway and let just see what happens by default without all the UI stuff.

**Comment by schmanu** [comment]
Yes sir! I would like to implement this in one! I'm just a bit busy at the moment. So I don't know for sure yet when I can get it done.

**Comment by bh2smith** [comment]
> Yes sir! I would like to implement this in one! I'm just a bit busy at the moment. So I don't know for sure yet when I can get it done.

No worries, it will likely be here for you. This issue has been open since early March anyway. I doubt that I'll ever get around to it unless I really need to send a bunch of NFTs.

**Comment by schmanu** [comment]
I finally have an update on this topic.

Today I built the first working version which combines NFTs and Asset Multisend. 
This makes it intuitive and easy to send NFTs, ERC20 Tokens and Native transfers in one transaction using multisend.

Here is a gif showing the new UI. I'm close to submitting the PR for review :)
![Uploading nfts.gif…]()

**Comment by schmanu** [comment]
The newest version has ERC721 and ERC1155 transfer support!

It's release to the gnosis app list is currently under review but its already merged into main branch.
