### ISSUE TITLE
Include FAQ in README

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/safe-airdrop#163]
Users have been reaching out to Gnosis Employees with a few common questions:

- What is the maximum number of addresses that tokens can be sent to in a single transaction using the CSV Airdrop app?
- In the token_address field, what address do I put if I am transferring ETH?

Perhaps it would be good to include a simple FAQ in the README. Will attempt this soon/later.

**Comment by schmanu** [comment]
closed by #292
