### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by john-light** [bh2smith/safe-airdrop#188]
This repository is currently missing a license file.

**Comment by bh2smith** [comment]
Thanks for reminding me. Will look into it and include one soon. Did you have something in mind for the code that might lead you to prefer one licence over another?

**Comment by john-light** [comment]
@bh2smith I am working with a team to deploy a self-hosted version of the Gnosis Safe interface, we want to use the CSV Airdrop app but one of the devs flagged that since there's no license here, default copyright rules apply and we cannot run our own copy without permission. So ideally MIT or any robust FOSS license should work for our use case.

**Comment by bh2smith** [comment]
Cool stuff, I'll get something together in the next day or so. Would it be enough to simply slap a licence on or would this also require a redeploy of our current version? I suppose it wouldn't matter since you'll be deploying your own.

**Comment by creed-victor** [comment]
> Cool stuff, I'll get something together in the next day or so. Would it be enough to simply slap a licence on or would this also require a redeploy of our current version? I suppose it wouldn't matter since you'll be deploying your own.

I believe it's enough to simply add a license on the repository in either case

**Comment by john-light** [comment]
> Would it be enough to simply slap a licence on or would this also require a redeploy of our current version? I suppose it wouldn't matter since you'll be deploying your own.

@bh2smith so this gets into some legal complexity regarding licensing. First, a disclaimer: I am not a lawyer, what follows is my amateur interpretation of relevant laws on the subject. If you want bulletproof legal advice, I suggest getting a lawyer who is familiar with copyright law in your jurisdiction.

I am not familiar with copyright law in your jurisdiction (Germany?) but in my jurisdiction (the United States) anything that is published without specifying an alternative license is published with full copyright "all rights reserved" restrictions. Per [standard open-source inbound=outbound practice](https://docs.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license) this means that all of the code you published in this repo was published under full copyright _and all of contributions you received from other contributors were also published under full copyright, unless otherwise specified_. This means that anyone who had a PR merged into this repo completely owns their contribution and can block its usage under copyright law.

In order for your relicense to MIT to have meaningful legal effect for your own contributions plus the contributions others have made until this point, you will need to contact everyone who had a PR merged in this repo and ask them to consent to the re-licensing of their work. For all of the contributions to be relicensed, you need consent from _all_ of the contributors. Any contributor who does not consent to the relicensing will retain full copyright ownership of their contribution and could block its usage on these grounds; you would have to remove these specific contributions to avoid them "poisoning" the rest of the project with their copyright restrictions.

What I suggest is writing a comment here or creating a new issue explaining that you are relicensing the project to MIT and need consent from all past contributors for the relicense to take effect. In the post, tag everyone who has ever had a PR (or a commit on a PR) accepted into this repo and ask them to reply with a comment in the affirmative saying "I consent to having all of my contributions made to this repository relicensed under the MIT license." This should be enough to ensure that there are no legal grounds for dispute later. Remember, any contributors that do not consent will have to have their contributions removed (or re-written in a legally distinct way) to ensure they cannot block usage or modification of their contribution on copyright grounds.

**Comment by bh2smith** [comment]
Hey @john-light, thanks for the details. So far only @schmanu and I have contributed to this project and he has approved the PR #189 which applied the changes. So I think we have the bases covered. Enjoy CSV Airdrop!

**Comment by lukasschor** [comment]
Agree with this change. I waive all rights resulting from my contributions when it comes to decisions around licensing of the software in this repository (in the past and future).
