### ISSUE TITLE
Dai transfer to 2 recipients, mainnet, metamask, doesn't work

### ISSUE THREAD

**Issue by adamstallard** [bh2smith/safe-airdrop#21]
```csv
token_address,receiver,amount,decimals
0x6b175474e89094c44da98b954eedeac495271d0f,0xDD00AB99Bff97E93AC1D0390F8e2ce41221050FE,21440,18
0x6b175474e89094c44da98b954eedeac495271d0f,0x77F6C1385eBd43ebe2B2de51C3E5d52cD4651278,19400,18
```
I realize the `decimals` column is unnecessary.

Here are the errors from the javascript console:
```javascript
Missing Infura key!
```
```javascript
Error: invalid BigNumber string (argument="value", value="2.144e+22", code=INVALID_ARGUMENT, version=bignumber/5.0.12)
```
```javascript
GET wss://mainnet.infura.io/ws/v3/undefined
```

The app worked 1 month ago (albeit with ETH, not DAI)

Using firefox, metamask

**Comment by bh2smith** [comment]
Hello @adamstallard and thanks for reporting. The first thing I can say is that the "missing infura key" has actually always been there and is unrelated to the problem you are experiencing here. 

I also noticed this issue on approximately the same day as you and reported here #20 (only 9 hours apart!)

My hunch at the moment is that there is some problem with BigNumber and large values (of magnitude ~10^4 * 10^18)

In the linked issue, I have included a transaction that went through where I was trying to send 3000 of one token and 5000 of another (both having 18 decimals). In my case, the transaction actually went through, but it sent infinitesimal amounts of these tokens (cf. linked transaction in the issue).

In your case, the same issue is happening for DAI (which wouldn't need a specified decimals column, but would probably have the same BigNumber problem). 

Will dig into this ASAP and find a fix. Cheers 🍻

**Comment by TripleSpeeder** [comment]
I'm still getting this error with the input by @adamstallard above:
`App.tsx:130 Error: invalid BigNumber string (argument="value", value="2.144e+22", code=INVALID_ARGUMENT, version=bignumber/5.0.12)`

I imported the app from `Qmbn7U6PjA2sBpU1yKhc6s6JxcXJd2Wuw8YAcDjeHBUK4F`, is this the latest hash?

**Comment by bh2smith** [comment]
@TripleSpeeder - That is the one. I will give it a closer look. Sorry for the inconvenience.

**Comment by bh2smith** [comment]
<img width="1309" alt="Screenshot 2021-05-05 at 09 54 01" src="https://user-images.githubusercontent.com/11778116/117111403-d3c49c80-ad87-11eb-98c1-14845385e3e7.png">

**Comment by schmanu** [comment]
I can only reproduce this error on the production build.
If I start the app locally using yarn start everything works fine.

![possibleProductionbuildIssue](https://user-images.githubusercontent.com/2670790/117128513-cdd9b600-ad9d-11eb-878a-8e177d52eac6.gif)

I will investigate this issue this week.

**Comment by bh2smith** [comment]
Hey @adamstallard and @TripleSpeeder. Our most recent deployment no longer has the issue with the sample file provided here. Happy Airdropping!
