### ISSUE TITLE
Support greater than 3-digit amounts

### ISSUE THREAD

**Issue by slgraham** [bh2smith/safe-airdrop#25]
Currently, I'm not able to transfer more than `amount = 999` tokens in a single transfer. This is with 18 decimals. 

Attempting to transfer `1000` tokens results in an error where the transaction is not generated within the Safe.
```
App.tsx:127 Error: invalid BigNumber string (argument="value", value="1e+21", code=INVALID_ARGUMENT, version=bignumber/5.0.12)
    at e.value (index.ts:205)
    at e.value (index.ts:217)
    at e.value (index.ts:221)
    at Function.value (bignumber.ts:230)
    at r.value (number.js:13)
    at array.js:41
    at Array.forEach (<anonymous>)
    at H (array.js:27)
    at r.value (tuple.js:19)
    at e.value (abi-coder.js:82)
```

The workaround is to transfer to the same address twice in a batch -- e.g. 2 transfers of `500` for a total transfer of `1000`. But that doesn't scale well to higher amounts like `10,000`.

**Comment by bh2smith** [comment]
This was fixed yesterday by #22. Please make sure you are using the newest version (see IPFS hash in readme).
