### ISSUE TITLE
Include native ETH transfer instruction on main interface

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/safe-airdrop#291]
Related, and possibly a better solution to,  #163 

on the right hand side of the app we should include a little text box with two very important FAQ facts:

1. To send ETHER leave the `token_address` field blank. See sample CSV file for example.
2. Please remember to leave the column headers (`token_address`, `receiver` and `amount`) as the first row of your CSV.

Have been getting a lot of questions/confusion about these two points from several places.

**Comment by schmanu** [comment]
This is done in the new help modal
