### ISSUE TITLE
Unresponsive File Upload & Drag+Drop

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/safe-airdrop#293]
Recently we have had a user (Chrome on Windows) who cannot upload the sample file:

When dragging the file in the drop box is highlighted in red indicating that the app already knows the file will not be supported.

<img width="431" alt="Screenshot 2021-11-17 at 10 33 07 AM" src="https://user-images.githubusercontent.com/11778116/142178817-9b8fc26f-81c2-4541-8a17-1481d1fec4e1.png">

I can only assume that the file was somehow changed by the OS after download. We have tried manually altering the file extension to be explicitly csv. but this may have resulted in bein renamed to `sample.csv.whatever_ms_added_cuz_it_sucks`. It is unclear if the actual file extension was modified by the operating system (since it doesn't display file extensions in the file navigator).

**Comment by schmanu** [comment]
@billyjitsu could you upload the file which is not working here so we can try to reproduce the issue?

**Comment by billyjitsu** [comment]
[wXdai test.csv](https://github.com/bh2smith/safe-airdrop/files/7690179/wXdai.test.csv)

Sure thing

**Comment by billyjitsu** [comment]
One thing to note, I'm on windows 10...  tried using brave, chrome and firefox .. if that helps

**Comment by bh2smith** [comment]
I am beginning to think this might be a windows thing (both cases so far have been there) and I none of us have ever tried this there. 

@billyjitsu could you also confirm that the same thing happens to you with the sample transfer file?

**Comment by schmanu** [comment]
I forgot to write it here. It was related to the .CSV file being created with excel. 
It was not comma separated but tab separated and was missing a column. 
I suggested to copy paste the file content as a workaround which helped. 
After my vacation I can try to reproduce this with a windows machine running excel and add a section into the FAQ if needed.

**Comment by bh2smith** [comment]
I wonder if we should try to support multiple "spreadsheet" formats.

**Comment by bh2smith** [comment]
This definitely appears to be a windows issue. I have another user reporting the same problem.

**Comment by schmanu** [comment]
> This definitely appears to be a windows issue. I have another user reporting the same problem.

Do you happen to have the file the user used? Or the workflow step by step? Was the file created in excel?

**Comment by billyjitsu** [comment]
So to follow up on my issue.  I believe it to be a pure being associated with MS excel issue.
I'll create a .csv file in "notepad" and associate the files with notepad is no issue.
I associate the .csv file with excel (opens with excel by default) and then I have issues.  I have to open with notepad, copy and paste for it to work.

**Comment by bh2smith** [comment]
I think this might have something to do with microsoft CSVs having `\r\n` for line breaks (i.e. with carriage return) while unix CSVs have `\n`. Just a thought.

**Comment by schmanu** [comment]
Closing as I didn't hear anything like it in a while
