### ISSUE TITLE
why are you limiting the app to specific networks?

### ISSUE THREAD

**Issue by sirpy** [bh2smith/safe-airdrop#324]
is there a technical reason why it shouldnt run on any deployment of gnosis safe on any network?
why does it have to support only "official" ones?

**Comment by bh2smith** [comment]
The app technically works on any EVM network that the safe is deployed. However, we do not host the app in the safe App Store. The App Store is hosted in a different repo (I'll try and remember to post the link here shortly) where the supported networks are configured. If there is a network missing that you're interested I. Having, you are more than welcome to include the necessary content here. Minimal info here is a token list (URL) for that network but I believe the application can even run without a provided token list (its just for displaying token icons). Also, it's nice to include a sample file specific to the network (although we haven't yet made this a requirement either). There is an open issue to include sample files for each network.

**Comment by bh2smith** [comment]
Here is the repo where networks are configured and an example issue to show how new networks are added

https://github.com/gnosis/safe-apps-list/issues/92

**Comment by sirpy** [comment]
@bh2smith i'm not asking about safe-apps-list
i'm asking why is supported networks hardcoded.. it simply prevents using it on other networks where gnosis-safe is installed without going through a PR here first
for example I wanted to try this app on fuse.io and i'm not able to. obviously i can fork or add it.
i'm just saying that I dont think it should be hardcoded by default

**Comment by bh2smith** [comment]
Ok so I see that it seems you are referring to this network map

https://github.com/bh2smith/safe-airdrop/blob/86de3971790c1baab7c6705eed4c5090aefb2491/src/hooks/token.ts#L13-L19

Note that we make use of this in a few different places

1. Here in the app interface: https://github.com/bh2smith/safe-airdrop/blob/86de3971790c1baab7c6705eed4c5090aefb2491/src/App.tsx#L54
2. Here when we fetch tokenlist https://github.com/bh2smith/safe-airdrop/blob/86de3971790c1baab7c6705eed4c5090aefb2491/src/hooks/token.ts#L29-L50

The second point is merely used in a log message so could be removed, but the first (I would have to ask @schmanu if its actually necessary).

We can look into refactoring "hard-coded" network map. We do also hope to introduce sample files for "known" networks.

I guess the only problem is item number 1 above which we can try to remove and then you should be free to run this without any hassle on any network!

**Comment by bh2smith** [comment]
I have created a PR that should open this up to all networks. Let me know if it works for you.

**Comment by sirpy** [comment]
cool thanks
