### ISSUE TITLE
Correct Native Token Symbol on all networks

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/safe-airdrop#338]
Based on Feedback [here](https://github.com/gnosis/safe-apps-list/issues/92#issuecomment-1011916061)
> The summary for native tokens on Xdai, Polygon & BSC shows them as ETH and I think it would be nice to provide feedback per native token

We do already have a network map with native token symbols in the code. I believe this was working in the past, but we must have accidentally removed this...

**Comment by schmanu** [comment]
Its part of the unmerged PR #317
