### ISSUE TITLE
Be less strict about the metadata interface for erc1155

### ISSUE THREAD

**Issue by schmanu** [bh2smith/safe-airdrop#341]
According to https://eips.ethereum.org/EIPS/eip-1155#metadata the following should be true for ERC1155 contracts:
>If the optional ERC1155Metadata_URI extension is included:
>
>   The ERC-165 supportsInterface function MUST return the constant value true if 0x0e89341c is passed through the interfaceID argument.

So currently we check each ERC1155 contract for this interface value and if it returns false we don't try to fetch metadata such as the token name / image of the token ID.

BUT as the real world shows. Most ERC 1155 contracts do not correctly implement ERC-165 and don't return `true` on the supportsInterface call. That's why we should not check for that interface anymore.

**Comment by bh2smith** [comment]
Seems reasonable to me.

**Comment by schmanu** [comment]
This was fixed in the mentioned PR.
