### ISSUE TITLE
How can I see ABI file of your smart contract

### ISSUE THREAD

**Issue by mohammadranjbarz** [bh2smith/safe-airdrop#354]
I want to process transaction events but I don't have your ABI files, how can I get that?

tx example:
https://blockscout.com/xdai/mainnet/tx/0x0c452a7c116adb6162390f342cee84175f34e3c1bc0015e6f82773a54ace3061/

**Comment by schmanu** [comment]
Hi,

we did not write our own smart contracts for this app.
It only works as a gnosis safe app and uses the smart contracts from the gnosis safe. 

To do this we use the https://github.com/gnosis/safe-apps-sdk/tree/master/packages/safe-apps-react-sdk 

For details on how the multi-sending of transactions works, please ask there.

**Comment by bh2smith** [comment]
All of what @schmanu said is true, however I can direct you toward the exact contracts which are used when building the call data for transaction execution. 

Specifically, we invoke the `execTransaction` method on your Gnosis Safe (contract available as a proxy at the address of your Gnosis Safe) or also available here: https://github.com/gnosis/safe-contracts/tree/main/contracts

Note that there are many different versions of the safe (but as far as I understand this particular method remains backwards compatible for quite some time).

We also invoke the `multiSend` method from `MultiSend.sol` available here: https://github.com/gnosis/safe-contracts/tree/main/contracts/libraries

Note also that there are several different versions on MultiSend.

We rely on the SafeSDK to provide us with the appropriate versions of each of the above contracts.

Finally, we also make use of the transfer (maybe `transferFrom`) methods from `ERC20.sol` for fungible tokens and `ERCxxx.sol` for non-fungible tokens. 

The transactions built from all of these contracts are composed in a form that looks somewhat like 

```
execTransaction(multiSend([transfer, transfer, transfer, ...., transfer]))
```

Cheers!

I hope this helps you find what you are looking for.

**Comment by bh2smith** [comment]
Closing this as the question has been "answered".
