### ISSUE TITLE
app stuck on loading tokens and balances on mainnet

### ISSUE THREAD

**Issue by schmanu** [bh2smith/safe-airdrop#357]
Right now the app seems to be stuck while loading the safes balances / tokens.
This should never happen as they are not necessary for the app to work. Instead we should display a warning that balance checks are not possible.

**Comment by bh2smith** [comment]
Looks like this particular uniswap token list has all the addresses:

https://gateway.ipfs.io/ipns/tokens.uniswap.org

**Comment by bh2smith** [comment]
Must be this one:

https://tokens.coingecko.com/uniswap/all.json

**Comment by bh2smith** [comment]
![Uploading Screen Shot 2022-02-11 at 12.24.08 PM.png…]()

**Comment by bh2smith** [comment]
Here are a bunch.

<img width="567" alt="Screen Shot 2022-02-11 at 12 26 26 PM" src="https://user-images.githubusercontent.com/11778116/153583706-4811537d-592a-4c05-966a-a7ef8dee4af2.png">

**Comment by bh2smith** [comment]
63 Matches.
<img width="891" alt="Screen Shot 2022-02-11 at 12 27 54 PM" src="https://user-images.githubusercontent.com/11778116/153583882-6e3054f1-86ad-4170-a753-3bfa06454057.png">
