### ISSUE TITLE
Strange `only positive amounts possible: NaN` errors.

### ISSUE THREAD

**Issue by nlordell** [bh2smith/safe-airdrop#358]
There appears to be false positive `Only posistive amounts possible: NaN` errors when using what appears to be a valid CSV:
```
token_type,token_address,receiver,amount,id
native,,0xd2F50B092ec32623c4955cEF4AE30C4699353735,29.047068684226095637,
native,,0x7942a2b3540d1eC40B2740896f87aEcB2a588731,16.185603484162678518,
native,,0x26029B63C7DBD0C4C04D7226C3e7de5EAb3DB3D8,29.000000000000000000,
```

Note that the no error appears in the top right corner, only inline in the CSV editor region. Additionally, the transfer list is also empty.

Additionally, AFAICT this doesn't always happen. For example if you refresh the app and paste in the ☝️ transfers, then it works. However, if you paste in the legacy format and then edit it to match ☝️, then this happens.

![image](https://user-images.githubusercontent.com/4210206/153576906-1f1cbe53-9687-4f0b-ae72-4399a8bb2ba6.png)

**Comment by schmanu** [comment]
Hey @nlordell ,
I found the issue. The `amount` column was renamed to `value` in the update.
The reason was simply that all contracts (erc20, erc1155) call it value and not amount.

The next update will make the CSV  backward compatible to prevent errors for users who have scripts creating CSVs, etc.

I will release it ASAP because of #357 breaking the app on mainnet

**Comment by bh2smith** [comment]
I think it should be renamed back to amount. Because it's not really a value.

**Comment by schmanu** [comment]
Not sure because when the transaction is submitted to be signed there will only be a value-field so users would hopefully be able to make that connection.

But with the next version both header columns will be allowed. So users can use whatever they prefer.

**Comment by nlordell** [comment]
🙈, didn't see the header renamed to `value`. Maybe the green checkmark in the top left should also indicate an error in this case?

**Comment by schmanu** [comment]
Fixed in next update
