### ISSUE TITLE
bep20 token type

### ISSUE THREAD

**Issue by negati-ve** [bh2smith/safe-airdrop#402]
does airdrop from gnosis safe support bep20 tokens? 
if yes, is it enough to be on bsc network and have token type as bep20 to process txns?

**Comment by schmanu** [comment]
Hey @negati-ve,

according to the [docs](https://academy.binance.com/en/glossary/bep-20) it's a standard which builds on top of erc20 and is compatible with the erc20 standard. 

So I would guess, that it should work. The Safe Airdrop uses  the [transfer](https://docs.openzeppelin.com/contracts/2.x/api/token/erc20#ERC20-transfer-address-uint256-) function of erc20 contracts to send the tokens.

Did you try using the app and see errors?

**Comment by negati-ve** [comment]
Tried and it works ! 
Tested with $1 drops to bep20 accounts
