### ISSUE TITLE
App not loading - IPFS issue

### ISSUE THREAD

**Issue by biafffff** [bh2smith/safe-airdrop#563]
Tried opening the app from Safe on both mainnet and Optimism, but it does not load and then I see this IPFS error message. 

<img width="617" alt="image" src="https://github.com/bh2smith/safe-airdrop/assets/26275332/4c6efec8-0754-4bfb-b5b5-a2d89b2d1439">

**Comment by schmanu** [comment]
This must have been a temporary issue. It works fine for me now!
