### ISSUE TITLE
[Bug] Upload from button acting weird

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/safe-airdrop#63]
When I use the "Upload File Button" I get my finder window opening again after selecting a file, and again (the second time it actually renders the file) and again. If I cancel on the third time everything is fine, but if I select the file the third time I get this error:

<img width="1034" alt="Screenshot 2021-05-20 at 21 27 07" src="https://user-images.githubusercontent.com/11778116/119037967-e3142e80-b9b2-11eb-88b0-f2636a08672b.png">

**Comment by schmanu** [comment]
This is so wierd. I can't reproduce this at all.
Does this happen to you every time you use that button or just sometimes?
Which Browser are you using?

**Comment by bh2smith** [comment]
Every time. I have only tried in Chrome. Can try some other browsers later.

**Comment by schmanu** [comment]
Ahh thats it. I tried it on Firefox. It seems to be a Chrome issue.

I'll try to figure it out now.

**Comment by schmanu** [comment]
Okay I got it fixed.

I added the commit to the linked PR #62 .
