### ISSUE TITLE
Code Editor sometimes misses input or moves the cursor around

### ISSUE THREAD

**Issue by schmanu** [bh2smith/safe-airdrop#74]
Somehow during validation (?) the editor gets stuck and misses some inputs. 
If its not easily fixable  we should validate everything on blur or make the debounce time longer?

**Comment by bh2smith** [comment]
I am not entirely sure what you mean by validating on "blur", but if you have an approach in mind feel free to try it out. I have not noticed this issue so far, is it reproducible?

**Comment by schmanu** [comment]
It's quite noticable when you for instance put some example file in and then try to edit the amount a bit.
Or write an entirely new line. Every now and then the cursor gets reset after the validation is through or one digit gets lost after the validation.

On Blur is the Event which is triggered, when the editor is not focused anymore. I'm not entirely sure yet how to fix it but I'll figure something out.

**Comment by schmanu** [comment]
I found a matching issue on the react ace editor: https://github.com/securingsincity/react-ace/issues/861

I will remove the debounce entirely for now. Because the suggested possible fix doesn't work. We already set the editorContent State in the first line of the change event.

**Comment by bh2smith** [comment]
Shouldn't this close automatically when the branch is merged? Or has that happened?
