### ISSUE TITLE
Provide Tool Tip with instructions

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/safe-airdrop#86]
Not sure how to best achieve this because we can't link to github readme from within the app.

Is there some way to embed a markdown file with instructions in the app page with a local reference?

**Comment by bh2smith** [comment]
Maybe this isn't necessary since the sample transfer file has an example.

Could we include commentary in the sample file that is ignored by the CSV parser?

**Comment by schmanu** [comment]
> Could we include commentary in the sample file that is ignored by the CSV parser?

The fast csv parser support commenting:
https://c2fo.github.io/fast-csv/docs/parsing/options/#comment

> Is there some way to embed a markdown file with instructions in the app page with a local reference?

There are react components to display markdown. But I dont know how nice it will look if we render them into a tooltip. We could try it though. 

But then again I think the app is fairly straight forward to use. There are more complex gnosis safe apps without any instructions whatsoever.

**Comment by bh2smith** [comment]
Maybe we can just try and go with some comments in the sample file.

**Comment by schmanu** [comment]
closing this as the new help modal solves this problem.
